### PR TITLE
128 fix login flow

### LINKED ISSUE #128: Unable to login due to index error
For an hour or so I'm unable to log in with the library due to an index error in the client.py file. (I'm working on a Linux VM)
I'm perfectly able to get inside the account from a mobile phone, website etc... even on the VM. I've found a similar previous issue but the suggestion (logging and accepting eventual popups) didn't work.

`  File "/home/virtual/Desktop/updated_version/stable/data_handling_layer/__init__.py", line 32, in handle_client
    client = mfp.Client(user_name, password)
  File "/home/virtual/.local/lib/python3.8/site-packages/myfitnesspal/client.py", line 69, in __init__
    self._login()
  File "/home/virtual/.local/lib/python3.8/site-packages/myfitnesspal/client.py", line 104, in _login
    authenticity_token = document.xpath(
IndexError: list index out of range`

### PR DESCRIPTION
**Pull request by hannahburkhardt**
Fixes #128 by updating the login flow:
- Load CSRF token
- Use new login URL
- Load authenticity token separately for set_measurements

### CODE REVIEW

**Comment by hannahburkhardt** [comment]
Looks like my changes for set_measurements ended up being very similar (identical?) to those made in #123

**Comment by realPrimoh** [comment]
I just tested this out on my end and it works again! Thanks so much @hannahburkhardt

**Comment by coddingtonbear** [comment]
Awesome; thanks for your help on this, @hannahburkhardt!  I'm sure you have more important things to work on in your life, but if you are interested in helping out with maintenance in the future, I'd love to give you merge access.

**Comment by hannahburkhardt** [comment]
@coddingtonbear I'm definitely interested in continuing to help out - I love this library and I use it all the time! 😁 I can't commit any particular amount of time of course, but if you'd like to give me access, that would be lovely.

**Pull request merged**
