### PR TITLE
switch to the measurements/new endpoint to permit arbitrary dates

### PR DESCRIPTION
**Pull request by dlgoodr**

### CODE REVIEW

**Comment by dlgoodr** [comment]
ok, I didn't fix the 2.7 builds.  I don't understand why travis is trying to pull in sphinx, but it appears to be a version problem: https://github.com/sphinx-doc/sphinx/issues/6470

**Comment by coddingtonbear** [comment]
Personally: kinda wouldn’t worry about Py2.7 — it has been EOL’d for a few months now, so we should probably just remove it from the build process.

**Comment by dlgoodr** [comment]
I wouldn't worry about py2 either, but it's your project <grin>. I'm just a sucker for a green build.

**Comment by dlgoodr** [comment]
Bump?

**Comment by coddingtonbear** [comment]
Thanks for the patch, @dlgoodr !

**Pull request merged**
